### PR TITLE
Revert use of Cstring to Ptr{UInt8}

### PR DESCRIPTION
**Pull request by odow**
@joaquimg could you try this one out? Let me know if you're using `Cstring` anywhere.

### CODE REVIEW

**Comment by odow** [comment]
We could also drop the `Cchar` => `UInt8` replacement, but that's a bit more breaking (because we use `UInt8('B')` explicitly in places) for minimal upside.
```julia
julia> Cchar
Int8
```

**Comment by joaquimg** [comment]
I think we can test until friday

**Comment by joaquimg** [comment]
this broke all our lic checks that relied on the userlic function

**Comment by odow** [comment]
Let's just leave it then. The generator script is a bit annoying, but it's written now.

**Pull request closed without merging**
