### PR TITLE
Breaking changes for MOI v0.10

### PR DESCRIPTION
**Pull request by metab0t**

### CODE REVIEW

**Comment by metab0t** [comment]
@odow @joaquimg The CI says that XPRESS cannot be loaded.

**Comment by odow** [comment]
So you need to push this to the `jump-dev` remote, instead of your personal one. 

Depending on how you `dev`'d the package, if you run `git remote -v` you might see
```
(base) oscar@Oscars-MBP Xpress % git remote -v
origin	https://github.com/jump-dev/Xpress.jl.git (fetch)
origin	https://github.com/jump-dev/Xpress.jl.git (push)
```
In this case, run `git push -u origin moi_v0.10`.

If you don't see a `jump-dev` remote and `origin` points to `https://github.com/metab0t/Xpress.jl`, run
```
git add remote jump-dev https://github.com/jump-dev/Xpress.jl.git
git push -u jump-dev moi_v0.10
```

**Comment by metab0t** [comment]
@odow So I should push this to jump-dev:moi_v0.10 and open a new PR?

**Comment by odow** [comment]
> So I should push this to jump-dev:moi_v0.10 and open a new PR?

Yes.

p.s. I sent you a message on discourse.

**Pull request closed without merging**
