### PR TITLE
Switch to using Conda binaries

### LINKED ISSUE #217: Renew CI license
Expired in Jan 2024: https://github.com/jump-dev/Xpress.jl/pull/213

### PR DESCRIPTION
**Pull request by odow**
Xpress publish binaries on Conda: https://anaconda.org/fico-xpress/xpress/files

They include a community license. If this works, it would greatly simplify things, and we'd be using their official binaries.

Closes #217

### CODE REVIEW

**Comment by odow** [comment]
@joaquim should I add Windows too? You'll probably want to test this with your PSR binaries and license before we merge.

**Comment by odow** [comment]
Windows support seemed problematic:

image

But I don't have a local Windows to debug.

**Comment by hellemo** [comment]
Very nice! FWIW I just did a quick test in Windows, and it seems to work perfectly. 

One caveat is that this is not a pristine system (just renamed my xpress folder), and the license file was found automatically. I suspect this might be from a previous install. What is the recommended way to provide the location of the license file when binaries are provided automatically?

**Comment by odow** [comment]
> I just did a quick test in Windows

Did you use one of the intermediate commits? I removed automatic from the latest commit.

We need to document, but it would be to set the `XPAUTH_PATH` pointing to the license file

**Comment by hellemo** [comment]
Weird, now it doesn't work anymore. I think maybe I was relying on the results from a previous Pkg.build for it to work, and switching between this branch and the release version didn't trigger a rebuild. 

When I lost contact with the license server, I did a manual build and since then it doesn't work anymore. (the need to rebuild after losing the license server is rather annoying).

**Comment by hellemo** [comment]
I think I figured it out, I reenabled the artifact for windows, then I get the same permissions error as you mentioned in an earlier comment. 
If I also set executable permissions to the library directory, I get it to work as expected:
```julia
elseif Sys.iswindows()  # Use the artifact instead.
    const xpressdlpath = joinpath(
        LazyArtifacts.artifact"xpresspy",
        joinpath("Lib", "site-packages", "xpress", "lib"),
    )
    chmod(dirname(xpressdlpath), 0o755; recursive=true) 
    const libxprs = joinpath(xpressdlpath, "xprs.dll")

```

**Comment by odow** [comment]
Oh nice! Let me try that

**Comment by odow** [comment]
Niiiiice.

One thing was talking to @simonbowly about. I wonder if it makes sense to split the binaries into an `Xpress_jll.jl` package. Then we can version the upstream binaries separately from `Xpress.jl`.

Otherwise everytime we change the Artifacts.toml it's a potential breaking change to Xpress.jl.

**Comment by odow** [comment]
See https://github.com/jump-dev/Xpress.jl/pull/220

That might take a while to tag and release etc, so we should do this PR first.

That'll let me make some progress on open issues, and we can decide what to do before we tag the next release.

**Comment by joaquimg** [comment]
I will test here to

**Comment by joaquimg** [comment]
I am not sure about the consequences of adding the artifacts.

Maybe a weakdep on Xpress_jll?

**Comment by odow** [comment]
The artifacts are lazy, so they should only be downloaded if you use them.

**Comment by odow** [comment]
I think ideally, we'd all just use Xpress_jll and Gurobi_jll, and version them appropriately. No more installation issues.

**Comment by odow** [comment]
@joaquimg can you try this branch? It should use the binaries only if `CI` is true.

**Comment by odow** [comment]
Closing in favor of #221

**Pull request closed without merging**
