### PR TITLE
Update constants and raw parameter for Xpress 8.12

### PR DESCRIPTION
**Pull request by henriquebecker91**
For now, I have just updated `common.jl` for the 8.12. Constants that existed before but were not generated for this new version were kept for backwards compatibility.

If someone could check which new constants are controls/parameters and of which type (`Int`, `String`, etc...) to add them to the respective `Dict`s I would be most grateful. I am not sure if I will have time to do this myself. I will probably be adding them manually when necessary in a patched personal version for now.

I did not update the lib file because it seems like a lot of the diff was caused by purely aesthetical changes (i.e., the name of the automatically generated arguments changed).

### CODE REVIEW

**Comment by joaquimg** [comment]
you should also run:
https://github.com/jump-dev/Xpress.jl/blob/master/scripts/build_param_control_dicts.jl

**Comment by henriquebecker91** [comment]
Ah, I think this is script is so new that I did not have it in my copy (forgot `git pull`). Will call it later today.

**Comment by henriquebecker91** [comment]
I did a pull, merge, and ran the script. The following lines do not exist in the new `Dict`s:

```julia
    "TREEPRESOLVE" => 8320,
    "TREEPRESOLVE_KEEPBASIS" => 8321,
    "TREEPRESOLVEOPS" => 832
```

Should these be kept with a comment saying they were kept because of backwards compatibility?

**Comment by joaquimg** [comment]
keeping would be good

**Comment by henriquebecker91** [comment]
I think this PR is now complete. I merged master into it, and I have updated the `Dict` code. The screenshot below shows the tests continue to pass:

2021-10-04-00:08:02_1920x1080

**Comment by henriquebecker91** [comment]
You were faster with your approval than me with my comment, XD.

**Pull request merged**
